kou7306/GeekLink_frontend

src/app/login/page.tsx, src/components/auth/LoginForm.tsx
emailとpasswordをuseStateで持つため、clientでなければいけない。
しかし、LoginButtonコンポーネントの中でserverコンポーネントを扱っている。
この問題をclientコンポーネントとserverコンポーネントを別々に実装することで、ログインフォームを実現しました。
=> ログインフォームを実装

src/app/login/page.tsx, src/app/sign-up/page.tsx, src/components/auth/LoginButton.tsx, src/components/auth/LoginForm.tsx, src/components/auth/SignOutButton.tsx
Sign Inの画面とSign Upのページを分けました。
LoginFromコンポーネントにpropsのsceanを追加しました。
"sign-in"か"sign-up"が渡されることを想定しています。
=> Separate signup from signin

src/app/message/page.tsx
=> トーク一覧画面を実装

package-lock.json, src/actions/users.ts, src/app/my-page/page.tsx, src/app/profile-initialization/page.tsx
import { getUuidFromCookie } from "@/actions/users";
const uuid = getUuidFromCookie();の一行で取得が可能です。
クライアントコンポーネントでは場合によっては
おそらくページ更新のタイミングの影響でuseEffectで囲う必要性があるかもしれません。
useEffect(() => {
const uuid = getUuidFromCookie();
}, []);
=> uuidをcookieに保存・取得・削除

package-lock.json, src/app/random-match/page.tsx, src/utils/getRandomMatchUser.ts
バックエンドのRandomMatchのAPIを繋げました。
データは取れているので、UIをどうするか…
=> RandomMatchのAPIを繋げる

package-lock.json, package.json, src/app/api/user/check/route.ts, src/app/page.tsx, yarn.lock
"/"にアクセスしようとしてログインしてあるけどnameがnullのユーザーは初期設定画面にリダイレクトさせる
=> nameがnullのユーザーは初期設定画面にリダイレクトさせる実装

src/app/profile-initialization/page.tsx, src/components/profile/ExperienceModal.tsx, src/components/profile/ExperienceSelect.tsx, src/components/profile/SnsIDModal.tsx, src/components/profile/TechModal.tsx, src/components/profile/TechSelect.tsx, src/components/profile/TopTechModal.tsx
初期設定画面とプロフィール編集画面において、フォームの送信ボタン以外のボタンでもフォームが送信されてしまうバグを修正しました。（buttonタグにtype="button"を付与）
=> submit属性のボタン以外でフォーム送信されるバグを修正

src/app/Header.tsx, src/app/group-list/page.tsx
めちゃくちゃ素朴なUIなんでまだ出したくはないのですが、一旦グループ作成ボタンも追加したいので基盤ということでプルリク出します
=> group list

src/components/auth/LoginForm.tsx, src/components/auth/SignInButton.tsx
- ゲストユーザーでのログインを実装しました。
https://github.com/user-attachments/assets/79dc8f20-bcd2-4b70-badf-0b3f6a26c6f5
=> ゲストログインを実装

package-lock.json, package.json, src/app/Providers.tsx, src/app/layout.tsx, src/components/profile/QiitaItem.tsx, src/components/profile/QiitaList.tsx, src/components/profile/RepositoryList.tsx, src/utils/formatDate.ts, types/qiitaArticle.ts, yarn.lock
=> Qiita記事一覧を表示

src/app/other/[uuid]/page.tsx, src/app/page.tsx, src/components/DailyRanking.tsx, src/components/Team.tsx, src/components/TeamRecruiting.tsx, src/components/TopUserRanking.tsx, src/components/TopUsersRanking.tsx, src/components/UserRanking.tsx, src/components/UsersRanking.tsx, src/components/timeline/TimeLineContainer.tsx
トップ画面右側のAPI繋ぎ込みとUI修正のプルリクエスト。
追記：自分の/other/[uuid]へ遷移する際、/my-pageへリダイレクトする処理を追加しました。
　　　ブランチ分けて実装するべきでしたが確認しやすかったため同ブランチで追加しています。
https://github.com/user-attachments/assets/15649dc8-dbbc-4481-bfcb-11311448f20a
=> トップ画面右側のUI修正

src/app/login/page.tsx, src/components/Team.tsx
トップ画面のチーム募集とログイン画面のUIの修正をしました。
表示する技術を3つに(使用技術が3つを超える場合には「...」を表示)
上部の白い余白部分(ヘッダー)を詰めるようにしました
=> トップ画面およびログイン画面の修正

src/components/profile/GitHubContributions.tsx, src/components/profile/PercentageOfLanguages.tsx, src/components/profile/ProfileCard.tsx, src/components/profile/QiitaList.tsx, src/components/profile/QiitaNumberOfContributions.tsx, src/components/profile/RepositoryList.tsx
- 共通で使っているコンポーネントのuuidの判定を変更しました。
=> Feature/my page UUID

src/components/profile/RepositoryGraph.tsx
=> グラフの右上にuncommitedが出ていたのを修正

src/app/random-match/page.tsx
=> ランダムマッチのカード

src/app/sign-up/page.tsx, src/components/profile/ProfileCard.tsx, src/components/profile/UserRank.tsx
bodyに渡すuuidをparamsから取得するように修正しました。
動作確認済みです。
Twitterライクでフォローボタンを作成しました。
https://github.com/user-attachments/assets/7a37dda0-fb4c-4604-ae6e-2805c1ab2b9d
=> フォローボタンの実装

src/app/group-list/page.tsx, src/components/groupChat/CreateGroup.tsx, src/components/groupChat/GroupChat.tsx
=> グループ一覧のUIを調整

src/app/suggest-users/page.tsx, src/components/modal/FilterSearch.tsx, src/components/suggest-users/Chips.tsx, src/components/suggest-users/UserCard.tsx, src/components/suggest-users/UsersPage.tsx
=> ユーザーサジェスト画面のデザイン修正

src/components/profile/ProfileCard.tsx
フォローボタンのUIを修正しました。
やったこと
・要素間の間隔を空ける
・ボタンの横幅を大きく
・文字間隔を少し広く
・文字サイズを小さく
https://github.com/user-attachments/assets/132d4e90-8d93-4a70-8b16-798b3168c669
=> フォローボタンのUI修正

src/app/random-match/page.tsx
- 背景が透けていたのを修正
- ボタンを押しても左右に飛ばなかった不具合を修正
=> ランダムマッチ画面のバグ修正

src/app/conversation/[partnerId]/page.tsx, src/app/group-list/page.tsx, src/app/ranking/page.tsx, src/components/activityLog/Activity.tsx, src/components/chat/Chat.tsx, src/components/chat/UserList.tsx, src/components/chat/UserSelectList.tsx, src/components/core/ComponentLoading.tsx, src/components/profile/GitHubContributions.tsx, src/components/profile/PercentageOfLanguages.tsx, src/components/profile/ProfileCard.tsx, src/components/profile/QiitaList.tsx, src/components/profile/QiitaNumberOfContributions.tsx, src/components/profile/RepositoryList.tsx, src/components/profile/UserRank.tsx, src/components/ranking/RankingPanels.tsx, src/components/timeline/TimeLineContainer.tsx, src/components/timeline/TimeLinePost.tsx, src/components/top-page/DailyRanking.tsx, src/components/top-page/EventsPage.tsx, src/components/top-page/SuggestUserList.tsx, src/components/top-page/TeamRecruiting.tsx, src/components/top-page/TopUsersRanking.tsx
=> ローディング画面を実装

package-lock.json, package.json, src/components/profile/RepositoryGraph.tsx, src/components/suggest-users/UserCard.tsx, src/components/timeline/PostModal.tsx, src/components/timeline/TimeLinePost.tsx, src/components/top-page/Team.tsx, yarn.lock
=> timeline修正

src/components/groupChat/CreateGroup.tsx, src/components/team-recruitments/CreateEventForm.tsx
- グループ作成のモーダルにキャンセルボタンを追加
- イベント作成ページにキャンセルボタンを追加
=> キャンセルボタンの追加

src/components/suggest-users/Chips.tsx
- おすすめユーザーのチップが出ていなかったのを修正しました。
=> おすすめユーザーのチップの修正

src/components/top-page/TopUserRanking.tsx, src/components/top-page/UserRanking.tsx
- ImageタグのアイコンをMUIのAvatarに置き換え
=> アイコンをavatarに置き換え

src/app/random-match/page.tsx, src/components/chat/UserList.tsx, src/components/chat/UserSelectList.tsx, src/components/profile/FollowNum.tsx, src/components/profile/ProfileCard.tsx, src/components/top-page/FollowerList.tsx, src/utils/addFollow.ts, src/utils/getMatchingUser.ts
やったこと
・いいねからフォロー機能への変更に伴うファイル・変数名の修正
・マイページへフォロー・フォロワー数を表示するコンポーネントを追加
・トップ画面で相互フォローのユーザーのアイコンが正しく表示されない問題を修正(https://github.com/kou7306/GeekLink_frontend/issues/275)
=> いいねからフォロー機能へのリプレイス

src/app/profile-initialization/page.tsx, src/components/profile/AffiliationInput.tsx, src/components/profile/AgeSelect.tsx, src/components/profile/DesireOccupationSelect.tsx, src/components/profile/EditorSelect.tsx, src/components/profile/ExperienceModal.tsx, src/components/profile/FacultySelect.tsx, src/components/profile/GraduateSelect.tsx, src/components/profile/HobbyInput.tsx, src/components/profile/MessageInput.tsx, src/components/profile/NameInput.tsx, src/components/profile/OccupationSelect.tsx, src/components/profile/PlaceSelect.tsx, src/components/profile/PortfolioInput.tsx, src/components/profile/ProfileEditForm.tsx, src/components/profile/QualificationInput.tsx, src/components/profile/SexSelect.tsx, src/components/profile/TechModal.tsx, src/components/profile/TechSelect.tsx, src/components/profile/TopTechModal.tsx
=> プロフィール編集の際の色修正

src/app/layout.tsx
=> ログイン画面でヘッダーが出ている不具合を修正

src/components/top-page/LeftSide.tsx
=> 文字のスタイル崩れを修正

src/app/profile-initialization/page.tsx, src/components/profile/FollowButton.tsx, src/components/profile/ProfileCard.tsx, src/components/suggest-users/UserCard.tsx
=> ユーザーカードにフォローボタンを追加

next.config.mjs
Reverts kou7306/GeekLink_frontend#353
=> Revert "cors"

src/app/my-page/[uuid]/page.tsx
Reverts kou7306/GeekLink_frontend#350
=> Revert "Feature/mypage"

next.config.mjs
Reverts kou7306/GeekLink_frontend#358
=> Revert "全て許可"
